### ISSUE TITLE
Problems with parking destinations and active routes

### ISSUE THREAD

**Issue by Iwan1803** [JustDen1234/FS19_AutoDrive_Sort#1]
Thanks for that tool and today i sorted my target points. Unfortunately i had a total chaos afterwards.
All assigned parking spaces are now wrong and the active routes also.
You should point out these problems.

If possible, you should also write the changes in the vehicles.xml to avoid this.

**Comment by Dennizzzzz** [comment]
Fixed the parking destinations in the vehicles.xml for worktools only in v1.0.2. Just found out i did forget the vehicles, so fixed that in v1.0.3.
