### ISSUE TITLE
If using folders, first sort by folder, then by destination

### ISSUE THREAD

**Issue by JustDen1234** [JustDen1234/FS19_AutoDrive_Sort#2]
When this is the list of destinations:
DA
DB
DC
DD
DE
DF
DG

And you create folders (and put the destinations in the folders):

Default  (folder)
  - DB
  - DF

AAA  (folder)
  - DA
  - DD

BBB  (folder)
  - DC
  - DE

CCC  (folder)
 - DG

This should be the order when cycle through them (the way you see them in the list). Thus Default first (is always the upper folder), etc.

**Comment by Iwan1803** [comment]
This sounds really good!

**Comment by JustDen1234** [comment]
Part of v1.0.6
