### ISSUE TITLE
Not processing a specific config file

### ISSUE THREAD

**Issue by dbump** [JustDen1234/FS19_AutoDrive_Sort#3]
AutoDriveSort skips the attached config.xml, which is an extensive route network that I did not create, but downloaded from a 3rd party.  I assume there is a formatting/data issue in the config, though AD does not seem to mind.  XML renamed to TXT in order to attach.
[AutoDrive_Slovak_Village_config.txt](https://github.com/JustDen1234/FS19_AutoDrive_Sort/files/5190332/AutoDrive_Slovak_Village_config.txt)

**Comment by Dennizzzzz** [comment]
@dbump I will fix it. But I already now what the problem is. If you just remove the first line, it should work.
In the xml files created by AutoDrive itself, the first line is not a part of the xml file. But as you stated, it is a 3rd party xml file.

**Comment by JustDen1234** [comment]
Part of v1.0.6
